sa_auth/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from .views import reception, logout_view

urlpatterns = patterns('',
    url(r'^$', reception, name='reception'),
    url(r'^auth/logout/$', logout_view, name='logout'),
)

superadmin/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'superadmin.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('sa_auth.urls', namespace='sa_auth', app_name='sa_auth')),
    url(r'^admin/', include(admin.site.urls)),
)

sa_auth/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractUser
from django.utils.translation import ugettext, ugettext_lazy as _


class User(AbstractUser):

    godfathers = models.ManyToManyField('self', null=True, blank=True,
                     symmetrical=False, related_name='nephews')

    def set_password(self, pwd):

        # Set pwd here.

        return super(User, self).set_password(pwd)

User._meta.get_field("first_name").blank = False
User._meta.get_field("last_name").blank  = False
User._meta.get_field("email").blank      = False

sa_auth/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from django.utils.translation import ugettext, ugettext_lazy as _

from .models import User


class UserForm(ModelForm):

    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password1 = forms.CharField(label=_("Nouveau mot de passe"), required=False,
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Nouveau mot de passe (confirmer)"), required=False,
                                widget=forms.PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 or password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2

    class Meta:

        model = User
        fields = ('first_name', 'last_name', 'email',)

sa_auth/views.py
# -*- coding: utf-8 -*-
#from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render_to_response, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout
from django.template import RequestContext
from django.contrib import messages

from .forms import UserForm


#@csrf_protect
def reception(request):

    if request.user.is_authenticated():

        form   = UserForm(instance=request.user)
        title  = 'Préférences'
        button = 'Modifier'

        if request.method == 'POST':

            form = UserForm(data=request.POST, instance=request.user)

            if form.is_valid():

                form.save()

                pwd = form.cleaned_data.get('password2')
                if pwd:
                    request.user.set_password(pwd)
                    request.user.save()
                    messages.success(request, 'Mot de passe modifié.')

                messages.success(request, 'Préférences modifiées.')

    else:

        title  = 'Login'
        button = 'Login'

        if request.method == 'POST':

            form = AuthenticationForm(data=request.POST)

            if form.is_valid():

                from django.contrib.auth import login
                user = form.get_user()
                login(request, user)
                form = UserForm(instance=user)

        else: form = AuthenticationForm()

    return render_to_response('reception.html', RequestContext(request, {'form': form, 'button': button, 'title': title}))


def logout_view(request):

    logout(request)

    return redirect('sa_auth:reception')

sa_auth/templates/reception.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{ title }}</title>
        {% load bootstrap3 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'sa_auth/css/style.css' %}" />
    </head>

    <body>
        {% if user.is_authenticated %}
        <p id="userbar">
            Bonjour {{ user }}
            {% if user.is_superuser %}<a type="button" class="btn btn-primary" href="{% url 'admin:index' %}">Admin</a>{% endif %}
            <a type="button" class="btn btn-danger" href="{% url 'sa_auth:logout' %}">Logout</a>
        </p>
        {% endif %}

        {% bootstrap_messages %}
    
        <div class="row">
            <div class="col-sm-6" id="logo">
            </div>
            <div class="col-sm-5">
                <form action="" method="post" class="form">
                    <h1>{{ title }}</h1>
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">{{ button }}</button>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </body>
</html>